version: '3'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27020:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=scrape_db
  

  facebook-scraper:
    image: achrefothmeni/facebook-scraper:latest
    container_name: facebook_scraper
    environment:
      - DATABASE_URL=mongodb://admin:admin@mongodb:27017/scrape_db?authSource=admin
    ports:
      - "8001:8000"
    restart: on-failure
    depends_on:
      - mongodb

volumes:
  mongodb_data: